[package]
name = "proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
anyhow = "1.0.0"
itertools = "0.10.3"
rayon = "1.5.3"
tqdm = "0.3.1"
